version: '2.1.{build}'
image: Visual Studio 2017

before_build:
- cmd: nuget restore

build_script:
    - cmd: dotnet pack -p:PackageVersion=%APPVEYOR_BUILD_VERSION%
    - cmd: dotnet pack -c Debug -p:PackageVersion=%APPVEYOR_BUILD_VERSION%


